mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from polls import views

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^questionlist/', include('polls.urls')),

    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^choices$', views.choiceindex, name='choiceindex'),
    url(r'^ak$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail , name = 'details') ,
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results , name = 'results') ,
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote , name = 'vote') ,

]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
    	return self.question_text


    #adding a custom database
    
    def was_published_recently(self):
    	return self.pub_date >= timezone.now() - datetime.timedelta(days = 1)



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
    	return self.choice_text

polls/views.py
from django.http import Http404,HttpResponse,HttpResponseRedirect
from django.template import RequestContext, loader

from django.shortcuts import get_object_or_404 , render
from .models import Question, Choice
from django.core.urlresolvers import reverse



def index(request):
	latest_question_list = Question.objects.order_by('-pub_date')[:5]

	template = loader.get_template('polls/index.html')
	context  = RequestContext(request,{'latest_question_list' : latest_question_list,})
	#the context is a dictionary mapping template variable names to python objects
	return HttpResponse(template.render(context))

#These polls have an argument, something different and new

def choiceindex(request):
	trending_choice_list = Choice.objects.order_by('votes')[:5]

	template1 = loader.get_template('polls/choiceindex.html')
	context1  = RequestContext(request,{'trending_choice_list' : trending_choice_list,})
	#the context is a dictionary mapping template variable names to python objects
	return HttpResponse(template1.render(context1))

def detail(request , question_id):
	try:
		question  = Question.objects.get(pk=question_id)
	except Question.DoesNotExist:
		raise Http404("Question does not exist")
	return render(request , 'polls/details.html', {'question': question} )
	#return HttpResponse("You're looking at question %s." % question_id)

def results(request , question_id):
	question  = get_object_or_404(Question,pk=question_id)
	return render(request, 'polls/details.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/choiceindex.html
{% if trending_choice_list %}
	<ul>
	{% for choice in trending_choice_list %}
		<li><a href="/polls/{{ question.id}}/">{{choice.choice_text}}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p> No Choices available </p>
{% endif %}	

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

polls/templates/polls/details.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
	<ul>
	{% for question in latest_question_list %}
		<li><a href="{% url 'details' question.id %}">{{question.question_text}}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p> No polls are available </p>
{% endif %}	

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{  choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes |pluralize }}</li>
    {%  endfor %}
</ul>

<a href="{% url 'polls:details' question.id%}"> Vote Again ? </a>